version: "3"

services:
  nginx-manager:
    image: jonasxpx/nginx-alpine-load-balance:1
    ports:
     - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: ["node.role == manager"]
  nginx-slave:
    image: jonasxpx/nginx-alpine-slave:1
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
